V.1.search.update row design
scbd/action-agenda-components pull request #16
Opened 2021-09-08 20:21 UTC by hmalik129

Slight clean of cod & added computed method for ".en" referencing during 'alt' designation for logo image

2021-09-13 17:33 UTC, randyhoulahan requested changes
Over all good.  Could you move the image to the body part of the card/row giving it 1 or 2 columns of the bootstrap 12 column grid?

2021-09-13 17:33 UTC, randyhoulahan commented on packages/search/src/components/List/Card/Body.vue
> +  if (this.country)
This if statement is not need as the short circuit on line 77 handles it.

2021-09-13 17:33 UTC, randyhoulahan commented on packages/search/src/components/List/Card/Body.vue
> +  let nameOfCountry = {}
I think we only actually need a let instead of const like 1% of the time.  Since the if below is not needed you can use const.

2021-09-13 17:33 UTC, randyhoulahan commented on packages/search/src/index.vue
> +import '@scbd/www-css/dist/style.css'
we should be inserting all the style already in the components main index.vue.  If something is not rendering properly we may need to rebuilt the scripts/index.css file.  What we do is when the component is built we we uncomment the bootstrap scss in the main file, then build the component and copy the index.css file into scripts for later use.

A little hackish for now but avoids duplicating all bootstrap for every built component.  The build extracts the css used by this component.

2021-09-13 18:44 UTC, closed without merging

2021-09-14 13:59 UTC, hmalik129 commented on packages/search/src/components/List/Card/Body.vue
> +  let nameOfCountry = {}
Oh okay. Yes that makes sense.

2021-09-14 15:28 UTC, hmalik129 commented on packages/search/src/index.vue
> +import '@scbd/www-css/dist/style.css'
Okay is it usually good practice to rebuild scripts/index.css as I have constantly rebuilt it rather than using the build in classes?