Editable-Form
scbd/action-agenda-components pull request #8
Opened 2021-07-26 19:32 UTC by ITsunilthapa

Created two fields for start date and end date on the form

2021-07-27 13:13 UTC, randyhoulahan requested changes
Thank you.  I think it may be nicer to have both properties on one row or on one row occupying the first 2/3's of the row.  The user will see the little date icon to select a date easier.  Please note how the data is formed in the debug box and ultimately sent to the server.    Instead of the LString object just a string property.  We may need to send it as { $date: '2021-07-27' } so mongo store the property as a date.  I will update the api and confirm.

I cleaned the branch and moved your work here to this branch https://github.com/scbd/action-agenda-components/tree/v1-form-date-range-props.  Please update on that branch.


It looks like the default html date select is fine and a separate component is not needed.

![Screen Shot 2021-07-27 at 9 03 34 AM](https://user-images.githubusercontent.com/13351610/127159571-4c4c4eb8-c162-44d7-a9fc-4ccb5bceae44.png)


![Screen Shot 2021-07-27 at 9 05 18 AM](https://user-images.githubusercontent.com/13351610/127158588-373aad15-7ba3-4350-aa75-cbe6e31a7075.png)

2021-07-27 13:13 UTC, randyhoulahan commented on packages/form/src/components/Action.vue
> +                startdate   : { [locale]: '' },
we always want to use camelCase in JS

2021-07-27 13:13 UTC, randyhoulahan commented on packages/form/src/components/Action.vue
> +          v-validate  ="'required|max:140'"
max:140 - is a length of string.  Not needed for date.  What validation does the v-validate library have for dates? https://vee-validate.logaretm.com/v2/guide/rules.html#date-format.  Reference the package.json, we use version 2.2.15 here.  Not the latest version is 4.

2021-07-27 13:13 UTC, randyhoulahan commented on packages/form/src/components/Action.vue
> +        <label :for="`action.attachments`"> {{ $t(`Attachment (s)`) }} </label>
thank you, my spelling is horrendous.

2021-07-30 14:16 UTC, ITsunilthapa commented
This branch will be closed as work has been moved to the new branch: https://github.com/scbd/action-agenda-components/tree/v1-form-date-range-props.

2021-07-30 14:16 UTC, closed without merging